# Biomes Configuration ${project.version}
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
#
# This indicates if advanced menu will be enabled in Biomes GUI when users choose
# biome or not. Advanced menu contains extra buttons that allows to choose biome
# change mode and range.
advanced-menu: true
#
# For advanced menu this indicate which mode will be active.
# If advanced menu is disabled or in biome set command update mode is not passed
# then update algorithm will use this value as update mode.
# Valid values are:
#     'ISLAND' - updates biome on whole island
#     'CHUNK' - updates biome on whole chunks around player
#     'RANGE' - updates biome by block in given range
default-mode: ISLAND
#
# For advanced menu this indicate how large range will be set on GUI opening.
# If advanced menu is disabled or in biome set command update range is not set
# then update algorithm will use this value as update range.
default-size: 3
#
# This indicates if changing biome will affect whole island or just protection range.
# Allows to fix issues when biome is changed in space between islands.
use-protection-range: false
#
# This indicates if biome on island must be restored to default biome, if
# island changes owner and it does not have biome set ability.
# 'true' means that biome will be reset.
reset-biomes: false
#
# This indicates cool down in seconds between users can change biomes on their island.
cooldown: 60
#
# This indicates tick counter between each background update task.
# This process load chunks that require biome update and change biome in it.
# Setting 0 will stop background task and biome will be updated only when loaded.
update-tick-counter: 5
#
# This variable allows to choose which biomes users can see in Biomes GUI.
# Valid values are:
#     'ALL' - there will be no hidden biomes. All biomes will be viewable in GUI.
#     'DEPLOYED' - shows all biomes that are deployed.
#     'ACCESSIBLE' - only biomes that is unlocked via permission or other unlock type will be visible in GUI.
#     'TOGGLEABLE' - there will be button in GUI that allows users to switch from ALL to ACCESSIBLE modes.
biomes-visibility: TOGGLEABLE
#
# This string allows to change element order in Biomes description. Each letter represents
# one object from Biomes description. If letter is not used, then its represented part
# will not be in description. If use any letter that is not recognized, then it will be
# ignored. Some strings can be customized via lang file under 'biomes.gui.biomes-description'.
# List of strings and their meaning:
#  - DESCRIPTION - description from biomes object
#  - ORIGINAL_BIOME - defined minecraft biomes name: '*.biome-name'
#  - REQUIRED_MONEY - requirements for biome change: '*.required-money'
#  - REQUIRED_LEVEL - requirements for biome change: '*.required-island-level'
#  - REQUIRED_PERMISSION - requirements for biome change: '*.required-permission'
lore:
  - DESCRIPTION
  - ORIGINAL_BIOME
  - REQUIRED_MONEY
  - REQUIRED_LEVEL
  - REQUIRED_PERMISSION
#
# This allows to change lore description line length. By default it is 25, but some server
# owners may like it to be larger.
lore-length: 25
#
# This list stores GameModes in which Biomes addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
